type command
args:
endargs
data:
enddata
​​​​​⁣⁣⁣​⁣​​⁣​​⁣⁣​​⁣​⁣⁣​​​⁣​​⁣​⁣​​⁣​​​⁣⁣​​⁣​​​⁣​​​⁣​​​⁣​⁣⁣⁣​​​​⁣​​⁣​⁣⁣⁣​⁣⁣​​​​⁣​⁣⁣⁣⁣​​⁣​⁣​⁣⁣​​⁣​​​⁣⁣⁣⁣​⁣​⁣​⁣​⁣​⁣​​​​​⁣⁣​​​​​​​​​⁣​⁣⁣⁣⁣⁣⁣⁣​⁣⁣​​⁣⁣​​​⁣⁣⁣⁣⁣⁣​​⁣​⁣​⁣⁣⁣⁣⁣⁣⁣​​⁣⁣⁣​​​⁣​⁣⁣​⁣⁣⁣⁣⁣⁣​​⁣⁣​⁣​​​⁣⁣⁣​​​⁣​⁣⁣⁣⁣⁣⁣⁣​⁣​⁣⁣⁣​​⁣⁣​⁣​⁣⁣⁣​​​⁣⁣⁣⁣⁣⁣⁣​⁣⁣⁣​​⁣​​​​⁣​​​​⁣​⁣⁣​​​​​​​⁣⁣⁣​​​⁣​​⁣​​⁣⁣⁣⁣⁣​​⁣⁣​⁣​⁣⁣⁣​​⁣​⁣​⁣​​⁣⁣⁣⁣​⁣​⁣​​​​⁣⁣​​​​⁣⁣​​​​⁣​⁣⁣​​​​⁣​⁣⁣​​⁣​​⁣​⁣⁣⁣⁣​⁣​​⁣⁣⁣⁣​​​​⁣​​​​⁣​​⁣⁣⁣⁣⁣⁣⁣⁣​⁣⁣​⁣​⁣⁣⁣​⁣​⁣⁣​​⁣⁣⁣⁣​⁣⁣⁣⁣⁣​⁣​​​​​​​⁣⁣⁣⁣​⁣⁣⁣⁣⁣​​⁣​​⁣​⁣⁣⁣⁣⁣⁣​​⁣⁣​​⁣​⁣​⁣⁣⁣⁣⁣⁣⁣​​⁣⁣⁣​⁣⁣⁣​​⁣​​⁣​​⁣​​​​​​​⁣⁣​​​​​​⁣⁣⁣⁣​⁣​⁣⁣⁣​⁣⁣⁣​⁣​​​​⁣⁣⁣⁣⁣⁣⁣​​​​main:
ASSIGN [W8#B$-=5wWzri4)$T!o9X-=5wWzC2nSVqu))1-=5wWz)@<}cs>s*s-N{289] 3
ASSIGN [o}KDF-N/*t<l4eCU/Q@{6-N/*t<Misc~<LJ3D-N/*t<oNt..get9L-G/p1>] 3
ASSIGN [N(AOL-0NZqc5rAsY*F%KC-0NZqc~YK!(.$aVc-0NZqc/j5fQ6t$W^-j^5vW] 3
ASSIGN [YJZ8)-?$oJ.v2w{PuWzNA-?$oJ.@>fO2{c)ya-?$oJ.lbBR>?cbFf-&MA{Y] 3
ASSIGN [!B!PI-|2:KaJ|#lINu#G9-|2:KaF3bZ?ANK2i-|2:Ka1a$o9ugrt&-FUzdx] 3
ASSIGN [C.s$v-+6w{Fp00Ljjo7fn-+6w{Fyq@^!^Af&t-+6w{F)rlp{1bS@N-TL9@w] 3
ASSIGN [XQ^^r-dpy6p+T$g^wKJLQ-dpy6pa~PnXe$ry2-dpy6p~9oDE.j(Pz-6emy=] 3
ASSIGN [f#OyP-C@wMPvQ@hTf6my.-C@wMPt(Op@71)XC-C@wMPn3dfQ|2ZGB-r*{MW] 3
ASSIGN [tBJN+-H$b:):2sSi=Ae9Z-H$b:)?9Ws}n+kTX-H$b:)La*+<S)0lo-eZ!Nx] 3
ASSIGN [G+Whx-&#C7NuMIOHFUgWR-&#C7NMZa74LpK$2-&#C7Ne0>wX7xma&-KHqno] 3
ASSIGN [zkp.q-Jj!TMFD0P%.O|+j-Jj!TMJCV$>aGSVV-Jj!TMFIl*H9>R3$-<041A] 3
ASSIGN [tuTf3-U3BEv1fK{M*G)WO-U3BEv4Xwnw{^P~Q-U3BEvQIU~/VbRfN-y!#p2] 3
ASSIGN [>8cqX-rX)m%ldkfWOw/AY-rX)m%|a.3<T7W.O-rX)m%<N(DHWN>QN-kTWq!] 3
ASSIGN [I.Rma-ZO6w/+r+fZ}FUQQ-ZO6w/QGL&X3|E9F-ZO6w//spxYd7B:b-3$/O3] 3
ASSIGN [ZYlxK-dw^P9hjrFpV3wdc-dw^P9K#vrJQ=SbB-dw^P9JTqi:BJ9FQ-bO5tg] 3
ASSIGN [ff:m?-5BqPy~35qy6M*Y&-5BqPymEUqfOAQ(U-5BqPyKV:C}QC@/p-^D4c$] 3
ASSIGN [pTdT6-UyhEgT+{R~>W{rO-UyhEgi34L)+Uwo}-UyhEgi{E^UcEjB_-=RYw6] 3
⁣⁣⁣⁣⁣​​​⁣⁣⁣​⁣​​⁣⁣​​​​​⁣​​​⁣​​⁣⁣⁣⁣⁣​​​​​⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣​⁣⁣​⁣⁣​⁣​⁣​​⁣​⁣⁣⁣⁣⁣⁣​⁣​⁣⁣​​⁣​​​⁣​​​⁣⁣​⁣​​​​​⁣⁣​⁣​​​​⁣⁣​⁣​​​⁣⁣⁣​​​​​​⁣​⁣⁣⁣⁣​⁣​⁣⁣​​⁣⁣​⁣⁣​⁣⁣⁣​​​⁣⁣⁣​⁣​⁣​​⁣⁣​​⁣⁣⁣​⁣​​⁣​⁣⁣​​​​​⁣​​⁣⁣​​⁣​⁣⁣⁣⁣​​⁣⁣⁣⁣⁣​⁣⁣​​⁣⁣⁣⁣⁣​⁣​​⁣​​⁣⁣​⁣⁣​⁣​​⁣⁣​​⁣​​​​⁣​​​​⁣​⁣​⁣⁣​⁣​​⁣​​⁣​​​⁣​⁣⁣⁣​​⁣​​⁣​⁣​⁣​⁣​⁣⁣⁣​​​⁣​⁣​​​⁣​​​​​​⁣⁣⁣⁣⁣​⁣​​​⁣⁣​​⁣​⁣⁣⁣⁣​​⁣⁣​​⁣⁣⁣​⁣⁣⁣​​⁣⁣⁣⁣​⁣​⁣​​⁣⁣​​⁣⁣⁣​​⁣​​​⁣⁣​⁣⁣​⁣​​​⁣​​⁣​​⁣⁣⁣​​​⁣​​​⁣⁣​​​​​⁣​​⁣⁣⁣⁣⁣⁣⁣⁣⁣​​​⁣​​​​⁣​⁣⁣​⁣⁣⁣​⁣​⁣​​⁣​⁣⁣⁣⁣​​​​​​​​​⁣⁣⁣​​⁣⁣⁣​​​⁣⁣⁣⁣⁣⁣​⁣​⁣⁣⁣​​⁣⁣​⁣​​⁣​⁣⁣​​​​⁣⁣​​​⁣​⁣​⁣​​⁣⁣​⁣⁣​​⁣⁣​​​​​⁣​⁣​​⁣​​⁣​​​⁣​⁣⁣​⁣⁣⁣⁣⁣endmain
