type command
args:
endargs
data:
enddata
​⁣​⁣⁣⁣​⁣⁣​​⁣​​​⁣⁣​⁣⁣​⁣⁣​⁣​​​⁣⁣⁣​​​⁣⁣​⁣⁣⁣⁣​​⁣​⁣⁣⁣​​​⁣​​​​⁣⁣​⁣⁣⁣​​⁣​​⁣​​​​⁣​​⁣⁣⁣⁣​​⁣​⁣​​​⁣​​​​​⁣​⁣⁣⁣​​​​⁣​​​​⁣​​​​​​​⁣⁣​⁣⁣⁣⁣​​​⁣​⁣​​⁣⁣⁣​​⁣​⁣​⁣⁣​⁣​⁣⁣⁣​⁣⁣​​​⁣​​⁣⁣​​⁣⁣⁣​​⁣⁣⁣⁣​​​⁣​⁣⁣⁣⁣⁣⁣​​⁣⁣​​​⁣​​​​⁣​⁣⁣​⁣​⁣​⁣⁣​⁣⁣​​​⁣⁣⁣​⁣⁣​​​​⁣⁣​​​​⁣​​⁣​​⁣⁣⁣​​​​⁣⁣⁣⁣⁣⁣⁣⁣​⁣​​⁣​​⁣⁣​​​​​⁣​​​​⁣​​⁣​​​⁣​⁣⁣​⁣​⁣⁣⁣​⁣​⁣​⁣​⁣⁣​⁣⁣​​​​⁣​​⁣​​​⁣⁣⁣​​⁣​⁣​​⁣⁣​​​⁣​​​⁣​​⁣⁣​​⁣​⁣⁣⁣​⁣⁣⁣⁣​​⁣⁣⁣⁣​⁣​​​⁣⁣​​⁣​⁣⁣⁣⁣​⁣​​​⁣⁣⁣​⁣​⁣⁣⁣​⁣⁣​​⁣⁣​⁣​⁣⁣​​​​⁣​⁣⁣⁣⁣​⁣​⁣​⁣​​​⁣⁣​⁣⁣⁣​​​⁣⁣​​​​​⁣​⁣⁣​⁣⁣⁣⁣⁣⁣​⁣⁣⁣​⁣​​​⁣​⁣​⁣⁣​​⁣​​​​⁣⁣​​​​​​​⁣​⁣⁣⁣​⁣⁣⁣⁣⁣⁣⁣​⁣​​⁣⁣⁣⁣​⁣⁣⁣⁣​​⁣​⁣⁣​⁣​⁣⁣​​⁣​⁣​​​⁣​main:
ASSIGN [0jMKV-V}xUZgtTmy>Z8*c-{uCpSe7ux6}1(N<-(%hEc.{@NoU:?Br-+k^bM] 3
ASSIGN [h<&9#-HP+:F*q5c<X:+4E-}_fXT=XYyo3rZe{-.jFeMOkdr2/bhHg-PNC~1] 3
ASSIGN [6vv**-jbmx~LldUXh$?Oq-yoGS9a%^1ilO38&-lwE~?z=I8&p.7.d-ApkL!] 3
ASSIGN [?jvTX-nIxFGZjay~pIHEL-!s3E1@953M&W*PR-J7BL(+#)1Ruuo^j-Ff$:M] 3
ASSIGN [Q{W4m-_/94C.g8L2~nLi~-s}u6gQ:hCz~D|~k-cnzTf4jwjpY$a<o-XbyI:] 3
ASSIGN [mAz3X-Gf4o$22TQRk?M0o-A*6J./fC@p!3pv/-.s8*.urwfd2~s3>-1Ko*7] 3
ASSIGN [wr9A3-ZgkU2RQ}=3wmiK@-bX5())o3M6FLkU7-Yv0!WW=|/=xLjDd-YwPcC] 3
ASSIGN [)*?wD-.HL:@!?OvilNi%.-R3rSlMItoiWh(33-C|B#8M?r:5VV^tq-__}>Z] 3
ASSIGN [6|ZA=-/a{+2!eI#9~Kn_1-)W65FB@./.e{OF!-ut?E9z80J0S2<#Y-hAGRY] 3
ASSIGN [_(68?-TxT82jM)Nx54n:w-2aFg)8yy{Us@/i8-UkI)bU#mpiz3A4c-3(Sa$] 3
ASSIGN [aMK!{-!TG%AIR/nh?Y^tW-X2Oh<drJp~w?B*g-inP?ez?&Nhv{zlM-e=F:7] 3
ASSIGN [mqr&5-o*/qnpSB)Asb&}v-nV9G^}|yCKngbnB-C?O|R4?GeVzw=N(-_f1Fs] 3
ASSIGN [b1Ss3->Uv!LT(y8^DHN/h-CGqVJh%NCv9xb2G-*pvr1Yd%fG^&s>Z-9Gr|3] 3
ASSIGN [HB?q:-u}:B@v3%}3=m+&x-dbvs0Ricam{8RdS-U6Yr|k(JRZEefXJ-FK38z] 3
ASSIGN [n=zyk-X/k3W)($o>5(8Uq-u9R^Z9b.n<HQIiv-YHr}.@^=+B3WHM*-g3rAa] 3
ASSIGN [y>I<R-wW>W|>N#.b{j2<p-BQ_SGYZ20Svx8tn-7dSVbyB#r(U+Ffa-4pX05] 3
ASSIGN [7A8fs-}b&nyZ<>A|?#mU<-1O|#dXv6RgWW+p5-txIPAp7oFynER*A-P:G4%] 3
⁣⁣⁣⁣⁣​​​⁣⁣⁣​⁣​​⁣⁣​​​​​⁣​​​⁣​​⁣⁣⁣⁣⁣​​​​​⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣​⁣⁣​⁣⁣​⁣​⁣​​⁣​⁣⁣⁣⁣⁣⁣​⁣​⁣⁣​​⁣​​​⁣​​​⁣⁣​⁣​​​​​⁣⁣​⁣​​​​⁣⁣​⁣​​​⁣⁣⁣​​​​​​⁣​⁣⁣⁣⁣​⁣​⁣⁣​​⁣⁣​⁣⁣​⁣⁣⁣​​​⁣⁣⁣​⁣​⁣​​⁣⁣​​⁣⁣⁣​⁣​​⁣​⁣⁣​​​​​⁣​​⁣⁣​​⁣​⁣⁣⁣⁣​​⁣⁣⁣⁣⁣​⁣⁣​​⁣⁣⁣⁣⁣​⁣​​⁣​​⁣⁣​⁣⁣​⁣​​⁣⁣​​⁣​​​​⁣​​​​⁣​⁣​⁣⁣​⁣​​⁣​​⁣​​​⁣​⁣⁣⁣​​⁣​​⁣​⁣​⁣​⁣​⁣⁣⁣​​​⁣​⁣​​​⁣​​​​​​⁣⁣⁣⁣⁣​⁣​​​⁣⁣​​⁣​⁣⁣⁣⁣​​⁣⁣​​⁣⁣⁣​⁣⁣⁣​​⁣⁣⁣⁣​⁣​⁣​​⁣⁣​​⁣⁣⁣​​⁣​​​⁣⁣​⁣⁣​⁣​​​⁣​​⁣​​⁣⁣⁣​​​⁣​​​⁣⁣​​​​​⁣​​⁣⁣⁣⁣⁣⁣⁣⁣⁣​​​⁣​​​​⁣​⁣⁣​⁣⁣⁣​⁣​⁣​​⁣​⁣⁣⁣⁣​​​​​​​​​⁣⁣⁣​​⁣⁣⁣​​​⁣⁣⁣⁣⁣⁣​⁣​⁣⁣⁣​​⁣⁣​⁣​​⁣​⁣⁣​​​​⁣⁣​​​⁣​⁣​⁣​​⁣⁣​⁣⁣​​⁣⁣​​​​​⁣​⁣​​⁣​​⁣​​​⁣​⁣⁣​⁣⁣⁣⁣⁣endmain
